const brandData = [
  {
    brandId: 'ID1',
    brandName: 'Prodsmiths',
    numberOfBrandUsers: 35,
    numberOfCustomers: 101,
    numberOfCustomerUsers: 401,
    numberOfActiveContracts: 362,
  },
  {
    brandId: 'ID2',
    brandName: 'Encodarlab',
    numberOfBrandUsers: 36,
    numberOfCustomers: 100,
    numberOfCustomerUsers: 400,
    numberOfActiveContracts: 361,
  },
  {
    brandId: 'ID3',
    brandName: 'Prodsmiths',
    numberOfBrandUsers: 35,
    numberOfCustomers: 101,
    numberOfCustomerUsers: 401,
    numberOfActiveContracts: 362,
  },
  {
    brandId: 'ID4',
    brandName: 'Encodarlab',
    numberOfBrandUsers: 36,
    numberOfCustomers: 100,
    numberOfCustomerUsers: 400,
    numberOfActiveContracts: 361,
  },
  {
    brandId: 'ID5',
    brandName: 'Prodsmiths',
    numberOfBrandUsers: 35,
    numberOfCustomers: 101,
    numberOfCustomerUsers: 401,
    numberOfActiveContracts: 362,
  },
  {
    brandId: 'ID6',
    brandName: 'Encodarlab',
    numberOfBrandUsers: 36,
    numberOfCustomers: 100,
    numberOfCustomerUsers: 400,
    numberOfActiveContracts: 361,
  },
  {
    brandId: 'ID7',
    brandName: 'Prodsmiths',
    numberOfBrandUsers: 35,
    numberOfCustomers: 101,
    numberOfCustomerUsers: 401,
    numberOfActiveContracts: 362,
  },
  {
    brandId: 'ID8',
    brandName: 'Encodarlab',
    numberOfBrandUsers: 36,
    numberOfCustomers: 100,
    numberOfCustomerUsers: 400,
    numberOfActiveContracts: 361,
  },
  {
    brandId: 'ID9',
    brandName: 'Prodsmiths',
    numberOfBrandUsers: 35,
    numberOfCustomers: 101,
    numberOfCustomerUsers: 401,
    numberOfActiveContracts: 362,
  },
  {
    brandId: 'ID10',
    brandName: 'Encodarlab',
    numberOfBrandUsers: 36,
    numberOfCustomers: 100,
    numberOfCustomerUsers: 400,
    numberOfActiveContracts: 361,
  },
  {
    brandId: 'ID11',
    brandName: 'Prodsmiths',
    numberOfBrandUsers: 35,
    numberOfCustomers: 101,
    numberOfCustomerUsers: 401,
    numberOfActiveContracts: 362,
  },
  {
    brandId: 'ID12',
    brandName: 'Encodarlab',
    numberOfBrandUsers: 36,
    numberOfCustomers: 100,
    numberOfCustomerUsers: 400,
    numberOfActiveContracts: 361,
  },
  {
    brandId: 'ID13',
    brandName: 'Prodsmiths',
    numberOfBrandUsers: 35,
    numberOfCustomers: 101,
    numberOfCustomerUsers: 401,
    numberOfActiveContracts: 362,
  },
  {
    brandId: 'ID14',
    brandName: 'Encodarlab',
    numberOfBrandUsers: 36,
    numberOfCustomers: 100,
    numberOfCustomerUsers: 400,
    numberOfActiveContracts: 361,
  },
  {
    brandId: 'ID15',
    brandName: 'Prodsmiths',
    numberOfBrandUsers: 35,
    numberOfCustomers: 101,
    numberOfCustomerUsers: 401,
    numberOfActiveContracts: 362,
  },
  {
    brandId: 'ID16',
    brandName: 'Encodarlab',
    numberOfBrandUsers: 36,
    numberOfCustomers: 100,
    numberOfCustomerUsers: 400,
    numberOfActiveContracts: 361,
  },
  {
    brandId: 'ID17',
    brandName: 'Prodsmiths',
    numberOfBrandUsers: 35,
    numberOfCustomers: 101,
    numberOfCustomerUsers: 401,
    numberOfActiveContracts: 362,
  },
  {
    brandId: 'ID18',
    brandName: 'Encodarlab',
    numberOfBrandUsers: 36,
    numberOfCustomers: 100,
    numberOfCustomerUsers: 400,
    numberOfActiveContracts: 361,
  },
  {
    brandId: 'ID19',
    brandName: 'Prodsmiths',
    numberOfBrandUsers: 35,
    numberOfCustomers: 101,
    numberOfCustomerUsers: 401,
    numberOfActiveContracts: 362,
  },
  {
    brandId: 'ID20',
    brandName: 'Encodarlab',
    numberOfBrandUsers: 36,
    numberOfCustomers: 100,
    numberOfCustomerUsers: 400,
    numberOfActiveContracts: 361,
  },
  {
    brandId: 'ID21',
    brandName: 'Prodsmiths',
    numberOfBrandUsers: 35,
    numberOfCustomers: 101,
    numberOfCustomerUsers: 401,
    numberOfActiveContracts: 362,
  },
  {
    brandId: 'ID22',
    brandName: 'Encodarlab',
    numberOfBrandUsers: 36,
    numberOfCustomers: 100,
    numberOfCustomerUsers: 400,
    numberOfActiveContracts: 361,
  },
  {
    brandId: 'ID23',
    brandName: 'Prodsmiths',
    numberOfBrandUsers: 35,
    numberOfCustomers: 101,
    numberOfCustomerUsers: 401,
    numberOfActiveContracts: 362,
  },
  {
    brandId: 'ID24',
    brandName: 'Encodarlab',
    numberOfBrandUsers: 36,
    numberOfCustomers: 100,
    numberOfCustomerUsers: 400,
    numberOfActiveContracts: 361,
  },
  {
    brandId: 'ID25',
    brandName: 'Prodsmiths',
    numberOfBrandUsers: 35,
    numberOfCustomers: 101,
    numberOfCustomerUsers: 401,
    numberOfActiveContracts: 362,
  },
  {
    brandId: 'ID26',
    brandName: 'Encodarlab',
    numberOfBrandUsers: 36,
    numberOfCustomers: 100,
    numberOfCustomerUsers: 400,
    numberOfActiveContracts: 361,
  },
  {
    brandId: 'ID27',
    brandName: 'Prodsmiths',
    numberOfBrandUsers: 35,
    numberOfCustomers: 101,
    numberOfCustomerUsers: 401,
    numberOfActiveContracts: 362,
  },
  {
    brandId: 'ID128',
    brandName: 'Encodarlab',
    numberOfBrandUsers: 36,
    numberOfCustomers: 100,
    numberOfCustomerUsers: 400,
    numberOfActiveContracts: 361,
  },
  {
    brandId: 'ID32',
    brandName: 'Prodsmiths',
    numberOfBrandUsers: 35,
    numberOfCustomers: 101,
    numberOfCustomerUsers: 401,
    numberOfActiveContracts: 362,
  },
  {
    brandId: 'ID33',
    brandName: 'Encodarlab',
    numberOfBrandUsers: 36,
    numberOfCustomers: 100,
    numberOfCustomerUsers: 400,
    numberOfActiveContracts: 361,
  },
  {
    brandId: 'ID34',
    brandName: 'Prodsmiths',
    numberOfBrandUsers: 35,
    numberOfCustomers: 101,
    numberOfCustomerUsers: 401,
    numberOfActiveContracts: 362,
  },
  {
    brandId: 'ID35',
    brandName: 'Encodarlab',
    numberOfBrandUsers: 36,
    numberOfCustomers: 100,
    numberOfCustomerUsers: 400,
    numberOfActiveContracts: 361,
  },
  {
    brandId: 'ID36',
    brandName: 'Prodsmiths',
    numberOfBrandUsers: 35,
    numberOfCustomers: 101,
    numberOfCustomerUsers: 401,
    numberOfActiveContracts: 362,
  },
  {
    brandId: 'ID37',
    brandName: 'Encodarlab',
    numberOfBrandUsers: 36,
    numberOfCustomers: 100,
    numberOfCustomerUsers: 400,
    numberOfActiveContracts: 361,
  },
  {
    brandId: 'ID38',
    brandName: 'Prodsmiths',
    numberOfBrandUsers: 35,
    numberOfCustomers: 101,
    numberOfCustomerUsers: 401,
    numberOfActiveContracts: 362,
  },
  {
    brandId: 'ID39',
    brandName: 'Encodarlab',
    numberOfBrandUsers: 36,
    numberOfCustomers: 100,
    numberOfCustomerUsers: 400,
    numberOfActiveContracts: 361,
  },
  {
    brandId: 'ID40',
    brandName: 'Prodsmiths',
    numberOfBrandUsers: 35,
    numberOfCustomers: 101,
    numberOfCustomerUsers: 401,
    numberOfActiveContracts: 362,
  },
  {
    brandId: 'ID41',
    brandName: 'Encodarlab',
    numberOfBrandUsers: 36,
    numberOfCustomers: 100,
    numberOfCustomerUsers: 400,
    numberOfActiveContracts: 361,
  },
  {
    brandId: 'ID42',
    brandName: 'Prodsmiths',
    numberOfBrandUsers: 35,
    numberOfCustomers: 101,
    numberOfCustomerUsers: 401,
    numberOfActiveContracts: 362,
  },
  {
    brandId: 'ID43',
    brandName: 'Encodarlab',
    numberOfBrandUsers: 36,
    numberOfCustomers: 100,
    numberOfCustomerUsers: 400,
    numberOfActiveContracts: 361,
  },
];

export default brandData;
